### ISSUE TITLE
    On HackRf One. examples/rx_threaded.rs does not seem to be deactivating/cleaning up the device on close

### ISSUE THREAD

**Issue by supr** [FutureSDR/seify#5]
Hello Folks,

I have been trying seify on HackRf one the past few days. While running some of your examples in the examples directory i noticed that rx_threaded.rs is not deactivating the active stream. The RX LED on the HackRf is still on even after the program is done executing.

Thanks.

**Comment by bastibl** [comment]
Hmm, could you please try the soapysdr bindings (e.g., the soapy-sdr-stream binary https://github.com/kevinmehall/rust-soapysdr/blob/master/src/bin/soapy-sdr-stream.rs) and see if this behaves similar. I guess that might be an issue of the underlying soapy bindings. Maybe they are missing some function calls when the device of the streamer get dropped.

**Comment by supr** [comment]
Hi @bastibl

I have verified this by running `soapy-sdr-stream` and can confirm that this problem doesn't happen. Where as when i run the `rx_threaded` in seify. I encounter this issue. It is reproducible.

Thanks.

**Comment by bastibl** [comment]
I see, the RX thread was not terminated but just killed when the main thread received ctrl-c. Can you try with the recent commit?
