### ISSUE TITLE
Error connecting input to PulseAudio server, Ubuntu24

### ISSUE THREAD

**Issue by springyworks** [FutureSDR/seify#8]
On Ubuntu24, running the rx_generics.rs main() example, i get an error from soapy, via soapysdr, I suppose:

```
[INFO] [UHD] linux; GNU C++ version 13.2.0; Boost_108300; UHD_4.6.0.0+ds1-5.1build4
driver:      Soapy
id:          "0"
info:        {}
sample rate: 3200000.0
frequency:   927000000.0
gain:        None
[INFO] Using format CF32.
Error: Soapy(Error { code: StreamError, message: "RtAudio init error 'RtApiPulse::probeDeviceOpen: error connecting input to PulseAudio server." })

```
Debug pinpointed in streamers.rs file
  ```
     /// Activate a stream. 
    /// Call `activate` to enable a stream before using `read()`
    fn activate(&mut self) -> Result<(), Error> {
        self.activate_at(None)  //*****************problem here
    }

    /// Activate a stream.
    /// Call `activate` to enable a stream before using `read()`
    /// # Arguments:
    ///   * `time_ns` -- optional activation time in nanoseconds from the time the function is
    ///   called.
    fn activate_at(&mut self, time_ns: Option<i64>) -> Result<(), Error>;

```

Ubuntu24 uses an PulseAudio emulator on top of Pipewire. Disabling pipewire and activating pulseaudio only is not an option, i did that before, it resulted in havoc . I think the problem of the error lies at soapy, I have no intention of delving into that.

**Comment by bastibl** [comment]
That's the joy so Soapy :-/ I assume you'd get similar problems with `SoapySDRUtil --probe`? Could you maybe just uninstall `soapysdr-module-audio`, if you don't need it? See my reply here: https://github.com/FutureSDR/FutureSDR/issues/138#issuecomment-2132091120

Or you add the argument: `-a soapy_driver=uhd` (after a `--`)

**Comment by springyworks** [comment]
i tried the `rx_generic ` example again with adviced `soapy_driver` arg and with and without `soapysdr-module-audio` installed.

The Error changed from the PulseAudio server thing  to KeyError , see below:
```
~/rust/repos/seify$ cargo run --example rx_generic -- -a soapy_driver=uhd 
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.87s
     Running `target/debug/examples/rx_generic -a soapy_driver=uhd`
[INFO] [UHD] linux; GNU C++ version 13.2.0; Boost_108300; UHD_4.6.0.0+ds1-5.1build4
Error: Soapy(Error { code: Other, message: 
"LookupError: KeyError: No devices found for ----->\nDevice Address:\n    driver: uhd\n    soapy_driver: uhd\n" })

attached the `SoapySDRUtil --probe` output .
[SoapySDRUtil probe Soapy.txt](https://github.com/FutureSDR/seify/files/15458459/SoapySDRUtil.probe.Soapy.txt)
-/-

**Comment by bastibl** [comment]
Soapy does not find an SDR. Do you have one connected? If you have an SDR connected, it is an issue with the driver or the Soapy module for your driver.

If you actually try to use your sound card as an SDR, you'd have to check how to use the Soapy audio module on top of pipewire.

**Comment by springyworks** [comment]
In the first place I want to see a spectrum of  (one ) of my  pulseaudio/pipewire audio source(s), radio-control is not a priority at the moment. More context: I have Wfview on Ubuntu24 which connects via wifi to my IC705 radio. Wfview , at its turn, can be accessed via hamlib for radio control, and for audio it relies on the/a linux audio infrastructure . Fldigi and WSJT-X can use this schema, but this was not out-of-the-box. 

btw. thanks for your efforts with these frameworks !
-/-

**Comment by springyworks** [comment]
Code below worked !
 

```
 dev.set_frequency(Rx, 0, 0.0)?;
 dev.set_sample_rate(Rx, 0, 48000.0)?;
...
  timeout_us : 300000 in rx.read(....)
```

1.  some lib's  needed to be installed : gnuplot, ..., ...
2. sudo apt install soapysdr-module-audio 

3. $>  cargo run --example rx_generic 
I get :
RtAudio pulse: _NOT_ running realtime scheduling
I get a window with a single shot spectrum. ;-)
In pavucontrol i see RTaudio listed under the Recording tab
-/-

**Comment by bastibl** [comment]
Great, I'll close the issue. Feel free to reopen if there are still problems.
